glibc: remove KISS_ROOT usage

diff --git a/overrides/core/glibc/files/locale-gen b/overrides/core/glibc/files/locale-gen
--- a/overrides/core/glibc/files/locale-gen
+++ b/overrides/core/glibc/files/locale-gen
@@ -1,9 +1,7 @@
 #!/bin/sh -e
 
-: "${KISS_ROOT:=/}"
-
-[ -r "$KISS_ROOT/etc/locale.gen" ] || {
-    printf "%s: error, cannot read '$KISS_ROOT/etc/locale.gen'\n" "$0" >&2
+[ -r /etc/locale.gen ] || {
+    printf "%s: error, cannot read '/etc/locale.gen\n" "$0" >&2
     exit 1
 }
 
@@ -12,8 +10,8 @@ while read -r line; do
     INPUTFILE="${INPUTFILE%%.*}"
     CHARMAPFILE="${line##* }"
     printf "Generating locale %s.%s\n" "$INPUTFILE" "$CHARMAPFILE"
-    localedef -i "$INPUTFILE" -f "$CHARMAPFILE" "$INPUTFILE.$CHARMAPFILE" --prefix="$KISS_ROOT" || {
+    localedef -i "$INPUTFILE" -f "$CHARMAPFILE" "$INPUTFILE.$CHARMAPFILE" || {
         printf "%s: error, generating locale %s.%s failed\n" "$0" "$INPUTFILE" "$CHARMAPFILE"
         exit 1
     }
-done < "$KISS_ROOT/etc/locale.gen"
+done < /etc/locale.gen
